import '@/assets/styles/global.css';
import Header from '@/components/common/Header';
import Sidebar from '@/components/common/Sidebar';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex">
        <Sidebar />
        <div className="pt-[60px] pl-[39px]">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
