import '@/assets/styles/global.css';
import Header from '@/components/common/Header';
import Sidebar from '@/components/common/Sidebar';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex min-h-screen w-screen bg-[url('/images/bg.png')] bg-cover">
          <Sidebar />
          <div className="sm:mr-[56px] sm:grow-1 sm:pt-[60px] sm:pb-[60px] sm:pl-[39px]">
            <Header />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
